language: go

go:
  - 1.8.x
  - tip

matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
